package models

import (
	"fmt"
	"strings"
)

// this file is generated by egoist.generators.structkit

type Op string

const (
	OpAdd Op = "add"
	OpSub Op = "sub"
	OpMul Op = "mul"
)


func (v Op) Valid() error {
	switch v {
	case OpAdd, OpSub, OpMul:
		return nil
	default:
		return fmt.Errorf("%q is invalid enum value of (add, sub, mul)", v)
	}
}

func (v *Op) UnmarshalJSON(b []byte) error {
	*v = Op(strings.Trim(string(b), `"`))
	return v.Valid()
}