package enums

import (
	"fmt"
	"strings"
)

// this file is generated by egoist.generators.structkit

type WeekDay string

const (
	WeekDayMonday WeekDay = "Monday"
	WeekDayTuesday WeekDay = "Tuesday"
	WeekDayWednesday WeekDay = "Wednesday"
	WeekDayThursday WeekDay = "Thursday"
	WeekDayFriday WeekDay = "Friday"
	WeekDaySaturday WeekDay = "Saturday"
	WeekDaySunday WeekDay = "Sunday"
)


func (v WeekDay) Valid() error {
	switch v {
	case WeekDayMonday, WeekDayTuesday, WeekDayWednesday, WeekDayThursday, WeekDayFriday, WeekDaySaturday, WeekDaySunday:
		return nil
	default:
		return fmt.Errorf("%q is invalid enum value of (Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday)", v)
	}
}

func (v *WeekDay) UnmarshalJSON(b []byte) error {
	*v = WeekDay(strings.Trim(string(b), `"`))
	return v.Valid()
}