package models

import (
	"github.com/podhmo/maperr"
	"encoding/json"
)

// this file is generated by egoist.generators.structkit

type Person struct {
	Name string `json:"name"`
	Age int `json:"age"`
	Memo *Memo `json:"memo"`
	Memo2 ***Memo `json:"memo2"`
	Memo3 ***Memo `json:"memo3"`
}

func (p *Person) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Name *string `json:"name"`// required
		Age *int `json:"age"`// required
		Memo *json.RawMessage `json:"memo"`
		Memo2 *json.RawMessage `json:"memo2"`// required
		Memo3 *json.RawMessage `json:"memo3"`// required
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil  {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Name != nil  {
			p.Name = *inner.Name
		} else  {
			err = err.Add("name", maperr.Message{Text: "required"})
		}
		if inner.Age != nil  {
			p.Age = *inner.Age
		} else  {
			err = err.Add("age", maperr.Message{Text: "required"})
		}
		if inner.Memo != nil  {
			p.Memo = &Memo{}
			if rawerr := json.Unmarshal(*inner.Memo, p.Memo); rawerr != nil  {
				err = err.Add("memo", maperr.Message{Error: rawerr})
			}
		}
		if inner.Memo2 != nil  {
			v0 := &Memo{}
			v1 := &v0
			p.Memo2 = &v1
			if rawerr := json.Unmarshal(*inner.Memo2, p.Memo2); rawerr != nil  {
				err = err.Add("memo2", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("memo2", maperr.Message{Text: "required"})
		}
		if inner.Memo3 != nil  {
			v0 := &Memo{}
			v1 := &v0
			p.Memo3 = &v1
			if rawerr := json.Unmarshal(*inner.Memo3, p.Memo3); rawerr != nil  {
				err = err.Add("memo3", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("memo3", maperr.Message{Text: "required"})
		}
	}

	return err.Untyped()
}

type Memo struct {
	Text string `json:"text"`
}

func (m *Memo) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Text *string `json:"text"`// required
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil  {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Text != nil  {
			m.Text = *inner.Text
		} else  {
			err = err.Add("text", maperr.Message{Text: "required"})
		}
	}

	return err.Untyped()
}