default: 00 01 02 03 04 05

00:
	$(MAKE) -C $(shell echo $@*/)
01:
	$(MAKE) -C $(shell echo $@*/)
02:
	$(MAKE) -C $(shell echo $@*/)
03:
	$(MAKE) -C $(shell echo $@*/)
04:
	$(MAKE) -C $(shell echo $@*/)
05:
	$(MAKE) -C $(shell echo $@*/)
