package main

import (
	"flag"
	"fmt"
	"os"
	"log"
	"m/internal"
)

// this package is generated by egoist.generate.clikit

// Option ...
type Option struct {
	Grumby bool // for `-grumby`
	Args []string // cmd.Args
}


func main() {
	opt := &Option{}
	cmd := flag.NewFlagSet("wire_example", flag.ContinueOnError)
	cmd.Usage = func() {
		fmt.Fprintln(cmd.Output(), `wire_example - google/wire event examples`)
		fmt.Fprintln(cmd.Output(), "")
		fmt.Fprintln(cmd.Output(), "Usage:")
		cmd.PrintDefaults()
	}
	cmd.BoolVar(&opt.Grumby, "grumby", false, "-")

	if err := cmd.Parse(os.Args[1:]); err != nil {
		if err != flag.ErrHelp {
			cmd.Usage()
		}
		os.Exit(1)
	}
	opt.Args = cmd.Args()
	if err := run(opt); err != nil {
		log.Fatalf("!!%+v", err)
	}
}

func run(opt *Option) error {
	v1 := internal.NewMessage()
	v2 := internal.NewGreeter(v1, opt.Grumby)
	v3, err := internal.NewEvent(v2)
	if err != nil  {
		return err
	}
	v3.Start()
	return nil
}