package main

import (
	"flag"
	"fmt"
	"os"
	"log"
	"time"
	"m/todo"
)

// this file is generated by egoist.generators.clikit

// Option ...
type Option struct {
	Args []string // cmd.Args
}


func main() {
	opt := &Option{}
	cmd := flag.NewFlagSet("todo", flag.ContinueOnError)
	cmd.Usage = func() {
		fmt.Fprintln(cmd.Output(), `todo - todo message`)
		fmt.Fprintln(cmd.Output(), "")
		fmt.Fprintln(cmd.Output(), "Usage:")
		cmd.PrintDefaults()
	}

	if err := cmd.Parse(os.Args[1:]); err != nil {
		if err != flag.ErrHelp {
			cmd.Usage()
		}
		os.Exit(1)
	}
	opt.Args = cmd.Args()
	if err := run(opt); err != nil {
		log.Fatalf("!!%+v", err)
	}
}

func run(opt *Option) error {
	s := new(todo.TodoStore)
	s.Filename = "todo.json"
	s.Now = time.Now

	if err := s.Load(); err != nil  {
		return err
	}
	for _, x := range opt.Args  {
		s.Add(x)
	}
	for _, x := range s.List()  {
		fmt.Println(x)
	}
	if err := s.Save(); err != nil  {
		return err
	}
	return nil
}