package main

import (
	"flag"
	"fmt"
	"os"
	"log"
	"github.com/podhmo/egoist/gofmtrpc"
)

// this file is generated by egoist.generators.clikit

// Option ...
type Option struct {
	Addr string // for `-addr`
	Sentinel string // for `-sentinel`
	Args []string // cmd.Args
}


func main() {
	opt := &Option{}
	cmd := flag.NewFlagSet("gofmtrpc", flag.ContinueOnError)
	cmd.Usage = func() {
		fmt.Fprintln(cmd.Output(), `gofmtrpc - gofmtrpc with JSONRPC`)
		fmt.Fprintln(cmd.Output(), "")
		fmt.Fprintln(cmd.Output(), "Usage:")
		cmd.PrintDefaults()
	}
	cmd.StringVar(&opt.Addr, "addr", ":9999", "-")
	cmd.StringVar(&opt.Sentinel, "sentinel", "", "-")

	if err := cmd.Parse(os.Args[1:]); err != nil {
		if err != flag.ErrHelp {
			cmd.Usage()
		}
		os.Exit(1)
	}
	opt.Args = cmd.Args()
	if err := run(opt); err != nil {
		log.Fatalf("!!%+v", err)
	}
}

func run(opt *Option) error {
	return gofmtrpc.Run(opt.Addr, opt.Sentinel)
}