from egoist.app import create_app, SettingsDict, parse_args

settings: SettingsDict = {"rootdir": "cmd/", "here": __file__}
app = create_app(settings)

# generated by egoist init new-command --name=hello
app.include("commands.hello")


if __name__ == "__main__":
    for argv in parse_args(sep="-"):
        app.run(argv)
