package models

import (
	"github.com/podhmo/maperr"
	"encoding/json"
)

// this file is generated by egoist.generators.structkit

type Person struct {
	Name string `json:"name"`
	Age int `json:"age"`
	*Memo `json:"memo"`  // {'inline': True, 'required': False, 'comment': '', 'tags': {'json': ['memo']}}
}

func (p *Person) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Name *string `json:"name"`// required
		Age *int `json:"age"`// required
		Memo *json.RawMessage `json:"memo"`
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil  {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Name != nil  {
			p.Name = *inner.Name
		} else  {
			err = err.Add("name", maperr.Message{Text: "required"})
		}
		if inner.Age != nil  {
			p.Age = *inner.Age
		} else  {
			err = err.Add("age", maperr.Message{Text: "required"})
		}
		if inner.Memo != nil  {
			p.Memo = &Memo{}
			if rawerr := json.Unmarshal(*inner.Memo, p.Memo); rawerr != nil  {
				err = err.Add("memo", maperr.Message{Error: rawerr})
			}
		}
	}

	return err.Untyped()
}

type Memo struct {
	Memo string `json:"memo"`
}

func (m *Memo) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Memo *string `json:"memo"`// required
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil  {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Memo != nil  {
			m.Memo = *inner.Memo
		} else  {
			err = err.Add("memo", maperr.Message{Text: "required"})
		}
	}

	return err.Untyped()
}