package models

import (
	"github.com/podhmo/maperr"
	"encoding/json"
)

// this file is generated by egoist.generators.structkit

type Person struct {
	Name string `json:"name"`
	Age int `json:"age"`
	Parents []*Person `json:"parents"`
	Parents2 []Person `json:"parents2"`
	Children []*Person `json:"children"`
	Children2 []Person `json:"children2"`
}

func (p *Person) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Name *string `json:"name"`// required
		Age *int `json:"age"`// required
		Parents *json.RawMessage `json:"parents"`// required
		Parents2 *json.RawMessage `json:"parents2"`// required
		Children *json.RawMessage `json:"children"`// required
		Children2 *json.RawMessage `json:"children2"`// required
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil  {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Name != nil  {
			p.Name = *inner.Name
		} else  {
			err = err.Add("name", maperr.Message{Text: "required"})
		}
		if inner.Age != nil  {
			p.Age = *inner.Age
		} else  {
			err = err.Add("age", maperr.Message{Text: "required"})
		}
		if inner.Parents != nil  {
			p.Parents = []*Person{}
			if rawerr := json.Unmarshal(*inner.Parents, &p.Parents); rawerr != nil  {
				err = err.Add("parents", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("parents", maperr.Message{Text: "required"})
		}
		if inner.Parents2 != nil  {
			p.Parents2 = []Person{}
			if rawerr := json.Unmarshal(*inner.Parents2, &p.Parents2); rawerr != nil  {
				err = err.Add("parents2", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("parents2", maperr.Message{Text: "required"})
		}
		if inner.Children != nil  {
			p.Children = []*Person{}
			if rawerr := json.Unmarshal(*inner.Children, &p.Children); rawerr != nil  {
				err = err.Add("children", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("children", maperr.Message{Text: "required"})
		}
		if inner.Children2 != nil  {
			p.Children2 = []Person{}
			if rawerr := json.Unmarshal(*inner.Children2, &p.Children2); rawerr != nil  {
				err = err.Add("children2", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("children2", maperr.Message{Text: "required"})
		}
	}

	return err.Untyped()
}